GET http://localhost:3000/api/produtos

###

POST http://localhost:3000/api/produtos
Content-Type: application/json

{
  "nome": "Prompt de musica para IA",
  "preco": 500,
  "descricao": "Prompt para criar musicas usando IA",
  "categoria": "Cursos"
}


###

DELETE  http://localhost:3000/api/produtos/12