GET http://localhost:3000/api/produtos

###

POST http://localhost:3000/api/produtos
Content-Type: application/json

{
  "nome": "Aulas de fotografia",
  "preco": 299.99,
  "descricao": "Seja profissional em fotografia com nossas aulas online.",
  "categoria": "Cursos"
}


###

DELETE  http://localhost:3000/api/produtos/12